# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --skip-lock
        
    - name: Lint with mypy
      run: |
        pip install mypy
        mypy fenix/ --strict --show-column-numbers --pretty --ignore-missing-imports --allow-subclassing-any --allow-untyped-decorations
        
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        # POSTGRES_DB - name for the default database that is created
        postgresql db: fenix
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: piesquared
        # POSTGRES_PASSWORD - superuser password
        postgresql password: test
    - name: Test with pytest
      run: |
        pip install pytest
        tests=(tests/*test.py)
        pipenv run python -m unittest $tests
